# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calculadora.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'calculadora.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63\x61lculadora.proto\x12\x0b\x63\x61lculadora\")\n\x07Valores\x12\x0e\n\x06valor1\x18\x01 \x01(\x01\x12\x0e\n\x06valor2\x18\x02 \x01(\x01\"\x1a\n\x08Resposta\x12\x0e\n\x06result\x18\x01 \x01(\x01\x32\xdd\x01\n\x0b\x43\x61lculadora\x12\x32\n\x03\x41\x64\x64\x12\x14.calculadora.Valores\x1a\x15.calculadora.Resposta\x12\x32\n\x03Sub\x12\x14.calculadora.Valores\x1a\x15.calculadora.Resposta\x12\x32\n\x03Mul\x12\x14.calculadora.Valores\x1a\x15.calculadora.Resposta\x12\x32\n\x03\x44iv\x12\x14.calculadora.Valores\x1a\x15.calculadora.Respostab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculadora_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VALORES']._serialized_start=34
  _globals['_VALORES']._serialized_end=75
  _globals['_RESPOSTA']._serialized_start=77
  _globals['_RESPOSTA']._serialized_end=103
  _globals['_CALCULADORA']._serialized_start=106
  _globals['_CALCULADORA']._serialized_end=327
# @@protoc_insertion_point(module_scope)
